version: "3.1"

services:
  spark-standalone-main:
    build:
      context: .
      dockerfile: spark.standalone.Dockerfile
    image: spark-standalone-main:1.0
    container_name: spark-standalone-main
    hostname: spark-standalone-main
    restart: unless-stopped
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./data/io:/root/data/io
    ports:
      - "9201:8080"
    networks:
      - hadoop
networks:
  hadoop: